### PR TITLE
Update module-info.java

### PR DESCRIPTION
**Pull request by regice202**

### CODE REVIEW

**Comment by regice202** [comment]
I'm unable to get this library working without it opening to ``javafx.graphics``.

**Comment by kinsleykajiva** [comment]
@dukke Please review PR .

**Comment by dukke** [comment]
Hi @regice202  and @kinsleykajiva,

This is not a bug. It's working as expected.

It's the other way around. You need to forcefully open javafx.graphics to com.pixelduke.fxthemes.

Please check the documentation: https://www.pixelduke.com/fxthemes/ and more specifically the final paragraph. You can also check the sample subproject to see a working example.

So now I'm wondering why have you overlooked this? Not criticizing or anything like that, just really want to know if I need to change the documentation or something else... (though I can't change the way javafx works though, namely the fact that this feature requires non public API)

I'm closing this PR as this is not an issue.

Thanks! :)

**Comment by regice202** [comment]
Hey @dukke!

It was some confusion on my end mainly, but the docs could be better. I understand you ask us to go here, and then here, and then here to find what we're looking for. But it would be nice if the samples were more front facing, instead of having to dig into the samples on the repo. I understand that this is standard practice for some, but it does make navigating the documentation and getting a project going a bit tougher and confusing.

What I would suggest is placing the pertinent information more towards the top of the documentation, **especially** about the opens and exports portion; show a sample of how that is done even. That should be like the **first** line/section of the API section, something like "Requirements". In the API sections below, it'd be nice to see some actual code samples of how each of those different effects are achieved.. Especially considering this is _**developer** documentation_. It _looks_ pretty, but functionally as it stands (in my opinion) it's not really telling you the information you **NEED** as a developer. Good documentation shows a developer **_what_** can be achieved, great documentation shows **_how_** it can be achieved and in a straight forward manner (not having to switch tabs and click links every 5 seconds).

**Comment by dukke** [comment]
I understand and you make some good points.

However, this is a free nonpaid open-source project that I'm doing in my free spare time. As such, time is limited and has to be spent wisely. I do whatever I can to optimize it. One of those things is using the samples as documentation which in this case they serve both for testing out features and also for documentation.
Between spending time in doing documentation (writing and keeping the docs up-to-date is time consuming) or spending time adding new features I think it's wiser to go for the later.

I've placed the "A few considerations" section further up in the documentation page as you suggested. Let me know if you have other suggestions that I can do quickly.

If you'd like to also contribute to the documentation that would be great.

Thanks @regice202 !

**Comment by regice202** [comment]
Hey @dukke!

I appreciate how you took my criticism! I may have come off a bit harsh, and you're entirely right; more features would be nice! You are also indeed doing this as a free open-source project, which awesome and I know I appreciate the work you're putting in on it. 🙂 I think even that small change could help quite a bit with getting people started on their own projects. The closer to the top, the more likely it's going to be found and read. I've also made another PR, hopefully you're checking over that as we speak and you can merge it! I think it's a pretty good PR and it will be very useful in future. Thanks again for your time and efforts!

**Comment by dukke** [comment]
Yes, that was a good call! Thanks for that @regice202 👌

**Pull request closed without merging**
